apiVersion: v1
kind: ConfigMap
metadata:
  name: imagegallery-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  YandexStorage__ServiceUrl: "https://storage.yandexcloud.net"
